### ISSUE TITLE
[CLOSED] Creating and editing a CMA case

### ISSUE THREAD

**Issue by benilovj** [alphagov/specialist-publisher#1]
<a href="https://github.com/elliotcm"><img src="https://avatars.githubusercontent.com/u/109225?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [elliotcm](https://github.com/elliotcm)**
_Thursday 13 February 2014 at 14:10 GMT_
_Originally opened as https://github.com/alphagov/specialist-publisher/pull/1_

---

https://www.pivotaltracker.com/story/show/65349700

Finder slug currently hardcoded to CMA.

---

_**[elliotcm](https://github.com/elliotcm)** included the following code: https://github.com/alphagov/specialist-publisher/pull/1/commits_

**Comment by benilovj** [comment]
<a href="https://github.com/elliotcm"><img src="https://avatars.githubusercontent.com/u/109225?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [elliotcm](https://github.com/elliotcm)**
_Thursday 13 February 2014 at 14:11 GMT_

---

@edds There seems to be a _lot_ of Bootstrap in this.  Do we need it all?

**Comment by benilovj** [comment]
<a href="https://github.com/elliotcm"><img src="https://avatars.githubusercontent.com/u/109225?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [elliotcm](https://github.com/elliotcm)**
_Thursday 13 February 2014 at 15:54 GMT_

---

Have spoken with @edds and he'd like to keep the whole lot so I'm going to leave Bootstrap alone, but it's a good target if we want to reduce load & parse times on CSS and JS.

**Comment by edds** [comment]
I do like a lot of bootstrap.
