### ISSUE TITLE
Timestamp is blank when republishing using SearchPresenter

### ISSUE THREAD

**Issue by fofr** [alphagov/specialist-publisher#1031]
We recently tried to republish all specialist documents to switch rendering app.

When running the republish task we had about 18,000 errors. We've only changed the string value of the rendering app, we believe this is an existing bug:
https://errbit.staging.publishing.service.gov.uk/apps/53204a310da1158686002516/problems/5909bbee6578636438388201

__ArgumentError: Timestamp is blank__
```
app/presenters/search_presenter.rb:24→ format_date
app/presenters/search_presenter.rb:18→ to_json
app/workers/republish_worker.rb:60→ rummager_add_document
app/workers/republish_worker.rb:20→ perform
```
https://github.com/alphagov/specialist-publisher/blob/master/app/presenters/search_presenter.rb#L24-L25

cc @tijmenb

**Comment by thomasleese** [comment]
No longer applies as publishing-api sends this to rummager.
