### ISSUE TITLE
Remove dependancy on govuk_frontend_toolkit

### ISSUE THREAD

**Issue by benilovj** [alphagov/specialist-publisher#273]
<a href="https://github.com/alicebartlett"><img src="https://avatars.githubusercontent.com/u/68009?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [alicebartlett](https://github.com/alicebartlett)**
_Tuesday 07 October 2014 at 10:26 GMT_
_Originally opened as https://github.com/alphagov/specialist-publisher/issues/273_

---

This app has a dependancy on govuk_frontend_toolkit which it probably shouldnt have as doesn't and shouldnt have the GOV.UK look and feel as it is an admin app. It is currently only using things like %contain-floats from the govuk_frontend_toolkit so we should remove this dependancy.

**Comment by benilovj** [comment]
<a href="https://github.com/edds"><img src="https://avatars.githubusercontent.com/u/35035?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [edds](https://github.com/edds)**
_Tuesday 07 October 2014 at 10:35 GMT_

---

I don't think I agree. Using things like the `%contain-floats` selector and the css3 shims from govuk_frontend_toolkit doesn't tie you to look like GOV.UK but lets you share the learnings and helpers we created for GOV.UK.

**Comment by benilovj** [comment]
<a href="https://github.com/alicebartlett"><img src="https://avatars.githubusercontent.com/u/68009?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [alicebartlett](https://github.com/alicebartlett)**
_Tuesday 07 October 2014 at 11:21 GMT_

---

@fofr any thoughts?

**Comment by benilovj** [comment]
<a href="https://github.com/fofr"><img src="https://avatars.githubusercontent.com/u/319055?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [fofr](https://github.com/fofr)**
_Tuesday 07 October 2014 at 11:30 GMT_

---

There isn't a clear boundary between things you should and shouldn't use from the frontend toolkit in an admin app, which will entangle the two approaches and complicate styles (I think there are some unavoidable clashes between the way Bootstrap solves a problem and the way the frontend toolkit does).

I think ultimately the admin template needs to adopt some of the frontend toolkit's tools and that it should be managed at the admin template level, rather than per app. For now that could just mean including `%contain-floats` within the admin template.

**Comment by benilovj** [comment]
<a href="https://github.com/edds"><img src="https://avatars.githubusercontent.com/u/35035?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [edds](https://github.com/edds)**
_Tuesday 07 October 2014 at 12:22 GMT_

---

Do you have any examples of the styles getting more complicated and confused? If there are examples of places you shouldn't use the toolkit helpers and use the Bootstrap equivalents instead then they should be documented. I don't believe copy pasting things from one of our toolkits into a project is the right way to work.

**Comment by benilovj** [comment]
<a href="https://github.com/bradwright"><img src="https://avatars.githubusercontent.com/u/1516?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [bradwright](https://github.com/bradwright)**
_Tuesday 07 October 2014 at 12:40 GMT_

---

What @edds says. The toolkit is just SCSS mix-ins - there's no reason any of them should be treading on any Bootstrap styles.

**Comment by benilovj** [comment]
<a href="https://github.com/fofr"><img src="https://avatars.githubusercontent.com/u/319055?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [fofr](https://github.com/fofr)**
_Tuesday 07 October 2014 at 13:44 GMT_

---

Looking at https://github.com/alphagov/specialist-publisher/blob/master/app/assets/stylesheets/_govspeak.scss

It seems that the frontend toolkit is being used to render govspeak in a way that must resemble the frontend (similar to the way Whitehall has done it I presume), so the look and feel is necessary in this situation. For this I think the toolkit is the best choice, and it should remain within specialist publisher.

There is a small risk that the toolkit helpers could be mistakenly used elsewhere within the app, eg applying core font styles in places that also inherit Bootstrap's design patterns (a specific example might be using core fonts within panels without adjusting Bootstrap's default padding or margin).

**Comment by benilovj** [comment]
We're cleaning up old issues as part of moving the Phase 2 of Specialist Publisher to a new repository. This has been open for a while and it doesn't sound like consensus was reached so I'm going to close this. Please feel free to reopen it if you don't agree...

**Comment by edds** [comment]
@benilovj It was only open for 3 days.

**Comment by benilovj** [comment]
@edds 3 days in this repo, 1.5 years in the old specialist publisher repo from which it was copied across by a script...
