### ISSUE TITLE
Problem with govspeak for inline attachments in lists

### ISSUE THREAD

**Issue by benilovj** [alphagov/specialist-publisher#620]
<a href="https://github.com/fofr"><img src="https://avatars.githubusercontent.com/u/319055?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [fofr](https://github.com/fofr)**
_Monday 21 December 2015 at 16:04 GMT_
_Originally opened as https://github.com/alphagov/specialist-publisher/issues/620_

---

(This is mostly a brain dump following some investigation on 2nd line.)

Following the Zendesk ticket https://govuk.zendesk.com/agent/tickets/1210622 it was found that the following govspeak is considered invalid by Specialist Publisher:

```
* [InlineAttachment:DHPC_Drug_shortage_InductOs_GB-NIR_CLEAN_FINAL.pdf]: Some text
```

After some investigation the error seems to happen only when all of the following are true:
- There is a list item that begins with a square bracket `* [`
- There is a closing square bracket immediately followed by a colon and a space: `]:`

Putting a character between the `*` and the `[` works, eg `* .[`. Removing the colon works. Using other characters that might be considered special, such as $ or `.` works fine. It was also noted that `\:` seems to escape the colon.

The shortest syntax that produces this bug is:
`* [a]:` (note the space)

**Comment by chrisroos** [comment]
Hey @tijmenb. I've just been investigating this same issue in manuals-publisher (https://github.com/alphagov/manuals-publisher/issues/620). As far as I can tell it's no longer a problem but wondered whether you had any more info given that you closed this version?
